// Absurd units for sharing your height: [singular, plural, height in meters].
// Heights are rough, typical values (things that are usually flat are "stacked";
// long things are "end to end" or "on end"). Add more freely.
window.CLIMBER_UNITS = [
  // People and characters
  ['Hugh Jackman', 'Hugh Jackmans', 1.88],
  ['Danny DeVito', 'Danny DeVitos', 1.47],
  ["Shaquille O'Neal", "Shaquille O'Neals", 2.16],
  ['Yao Ming', 'Yao Mings', 2.29],
  ['Peter Dinklage', 'Peter Dinklages', 1.35],
  ['Robert Wadlow (tallest man ever)', 'Robert Wadlows (tallest man ever)', 2.72],
  ['average human', 'average humans', 1.7],
  ['hobbit', 'hobbits', 1.07],
  ['Yoda', 'Yodas', 0.66],
  ['Bigfoot (estimated)', 'Bigfoots (estimated)', 2.4],
  ['average snowman', 'average snowmen', 1.5],
  ['garden gnome', 'garden gnomes', 0.3],
  ['Barbie doll', 'Barbie dolls', 0.29],
  ['LEGO minifigure', 'LEGO minifigures', 0.04],

  // Animals
  ['African bush elephant', 'African bush elephants', 3.2],
  ['giraffe', 'giraffes', 5.5],
  ['ostrich', 'ostriches', 2.5],
  ['emu', 'emus', 1.75],
  ['emperor penguin', 'emperor penguins', 1.15],
  ['flamingo', 'flamingos', 1.2],
  ['kiwi bird', 'kiwi birds', 0.4],
  ['chihuahua', 'chihuahuas', 0.2],
  ['corgi', 'corgis', 0.27],
  ['dachshund', 'dachshunds', 0.2],
  ['Great Dane', 'Great Danes', 0.8],
  ['house cat', 'house cats', 0.25],
  ['hamster', 'stacked hamsters', 0.05],
  ['hedgehog', 'stacked hedgehogs', 0.1],
  ['meerkat on lookout', 'meerkats on lookout', 0.3],
  ['capybara', 'capybaras', 0.55],
  ['alpaca', 'alpacas', 0.9],
  ['llama', 'llamas', 1.8],
  ['Shetland pony', 'Shetland ponies', 1.0],
  ['horse', 'horses', 1.6],
  ['moose', 'moose', 1.9],
  ['red kangaroo', 'red kangaroos', 1.5],
  ['silverback gorilla', 'silverback gorillas', 1.7],
  ['grizzly bear standing up', 'grizzly bears standing up', 2.4],
  ['polar bear standing up', 'polar bears standing up', 2.5],
  ['narwhal tusk', 'narwhal tusks', 2.5],
  ['Komodo dragon on its tail', 'Komodo dragons on their tails', 2.6],
  ['Tyrannosaurus rex (at the hip)', 'Tyrannosaurus rexes (at the hip)', 3.7],
  ['blue whale balanced on its tail', 'blue whales balanced on their tails', 25],
  ['garden snail', 'stacked garden snails', 0.03],

  // Food and drink
  ['marshmallow', 'stacked marshmallows', 0.03],
  ['Big Mac', 'stacked Big Macs', 0.08],
  ['Oreo', 'stacked Oreos', 0.01],
  ['pancake', 'stacked pancakes', 0.012],
  ['donut', 'stacked donuts', 0.03],
  ['slice of toast', 'stacked slices of toast', 0.015],
  ['pizza box', 'stacked pizza boxes', 0.05],
  ['soda can', 'stacked soda cans', 0.122],
  ['Pringles can', 'stacked Pringles cans', 0.24],
  ['banana', 'bananas end to end', 0.18],
  ['baguette', 'baguettes end to end', 0.65],
  ['hot dog', 'hot dogs end to end', 0.15],
  ['watermelon', 'stacked watermelons', 0.3],
  ['pineapple', 'stacked pineapples', 0.3],
  ['chicken egg', 'stacked chicken eggs', 0.06],
  ['ostrich egg', 'stacked ostrich eggs', 0.15],
  ['cereal box', 'stacked cereal boxes', 0.3],
  ['ketchup bottle', 'stacked ketchup bottles', 0.2],

  // Small stuff
  ['LEGO brick', 'stacked LEGO bricks', 0.0096],
  ['credit card', 'stacked credit cards', 0.00076],
  ['penny', 'stacked pennies', 0.0015],
  ['poker chip', 'stacked poker chips', 0.0033],
  ['DVD', 'stacked DVDs', 0.0012],
  ['hockey puck', 'stacked hockey pucks', 0.0254],
  ['AA battery', 'AA batteries end to end', 0.05],
  ["Rubik's Cube", "stacked Rubik's Cubes", 0.057],
  ['rubber duck', 'stacked rubber ducks', 0.09],
  ['golf ball', 'stacked golf balls', 0.043],
  ['ping pong ball', 'stacked ping pong balls', 0.04],
  ['tennis ball', 'stacked tennis balls', 0.067],
  ['baseball', 'stacked baseballs', 0.074],
  ['soccer ball', 'stacked soccer balls', 0.22],
  ['bowling ball', 'stacked bowling balls', 0.218],
  ['bowling pin', 'stacked bowling pins', 0.38],
  ['pencil', 'pencils end to end', 0.19],
  ['crayon', 'crayons end to end', 0.09],
  ['Sharpie', 'Sharpies end to end', 0.14],
  ['smartphone', 'smartphones end to end', 0.15],
  ['toilet paper roll', 'stacked toilet paper rolls', 0.11],
  ['shoebox', 'stacked shoeboxes', 0.12],

  // Household and street
  ['toaster', 'stacked toasters', 0.2],
  ['microwave', 'stacked microwaves', 0.3],
  ['washing machine', 'stacked washing machines', 0.85],
  ['refrigerator', 'stacked refrigerators', 1.75],
  ['IKEA Billy bookcase', 'stacked IKEA Billy bookcases', 2.02],
  ['front door', 'front doors', 2.03],
  ['shopping cart', 'stacked shopping carts', 1.0],
  ['traffic cone', 'stacked traffic cones', 0.7],
  ['fire hydrant', 'stacked fire hydrants', 0.7],
  ['basketball hoop', 'basketball hoops', 3.05],
  ['shipping container', 'stacked shipping containers', 2.59],
  ['double-decker bus', 'stacked double-decker buses', 4.4],
  ['school bus on end', 'school buses on end', 12],
  ['Olympic diving platform', 'Olympic diving platforms', 10],

  // Trophies
  ['Oscar statuette', 'Oscar statuettes', 0.343],
  ['FIFA World Cup trophy', 'FIFA World Cup trophies', 0.368],
  ['Stanley Cup', 'Stanley Cups', 0.896],

  // Landmarks and giants
  ['Stonehenge stone', 'Stonehenge stones', 4.1],
  ['Christ the Redeemer', 'Christ the Redeemers', 30],
  ['Statue of Liberty (no pedestal)', 'Statues of Liberty (no pedestal)', 46],
  ['Leaning Tower of Pisa', 'Leaning Towers of Pisa', 56],
  ['General Sherman tree', 'General Sherman trees', 84],
  ['Big Ben tower', 'Big Ben towers', 96],
  ['Saturn V rocket', 'Saturn V rockets', 111],
  ['Hyperion (tallest tree)', 'Hyperions (tallest tree)', 116],
  ['Great Pyramid of Giza', 'Great Pyramids of Giza', 139],
  ['Washington Monument', 'Washington Monuments', 169],
  ['Eiffel Tower', 'Eiffel Towers', 330],
  ['Empire State Building', 'Empire State Buildings', 381],
  ['Burj Khalifa', 'Burj Khalifas', 828],
  // More people and characters
  ['Michael Jordan', 'Michael Jordans', 1.98],
  ['LeBron James', 'LeBron Jameses', 2.06],
  ['Victor Wembanyama', 'Victor Wembanyamas', 2.24],
  ['Usain Bolt', 'Usain Bolts', 1.95],
  ['Simone Biles', 'Simone Bileses', 1.42],
  ['Lionel Messi', 'Lionel Messis', 1.7],
  ['Abraham Lincoln', 'Abraham Lincolns', 1.93],
  ['Napoleon', 'Napoleons', 1.69],
  ['Peter the Great', 'Peters the Great', 2.03],
  ['André the Giant', 'André the Giants', 2.24],
  ['Rumeysa Gelgi (tallest woman)', 'Rumeysa Gelgis (tallest woman)', 2.15],
  ['newborn baby', 'newborn babies', 0.5],
  ['toddler', 'toddlers', 0.85],
  ['Shrek', 'Shreks', 2.13],
  ['Mario', 'Marios', 1.55],
  ['Big Bird', 'Big Birds', 2.49],
  ['Darth Vader', 'Darth Vaders', 2.02],
  ['Chewbacca', 'Chewbaccas', 2.28],
  ['Hagrid (book version)', 'Hagrids (book version)', 3.5],
  ['Optimus Prime', 'Optimus Primes', 8.5],
  ['Iron Giant', 'Iron Giants', 15],
  ['Stay Puft Marshmallow Man', 'Stay Puft Marshmallow Men', 34],
  ['Godzilla', 'Godzillas', 108],
  ['The Thinker statue', 'Thinker statues', 1.86],
  ["Michelangelo's David", "Michelangelo's Davids", 5.17],
  ['Venus de Milo', 'Venuses de Milo', 2.04],
  ['Manneken Pis', 'Manneken Pises', 0.61],
  ['Little Mermaid statue', 'Little Mermaid statues', 1.25],
  ['Easter Island moai', 'Easter Island moai', 4],

  // More animals
  ['lion', 'lions', 1.2],
  ['tiger', 'tigers', 1.0],
  ['cheetah', 'cheetahs', 0.8],
  ['gray wolf', 'gray wolves', 0.8],
  ['red fox', 'red foxes', 0.4],
  ['raccoon', 'stacked raccoons', 0.3],
  ['hippopotamus', 'hippopotamuses', 1.5],
  ['rhinoceros', 'rhinoceroses', 1.8],
  ['camel', 'camels', 2.0],
  ['zebra', 'zebras', 1.4],
  ['okapi', 'okapis', 1.6],
  ['bison', 'bison', 1.8],
  ['giant panda', 'giant pandas', 0.8],
  ['chimpanzee', 'chimpanzees', 1.2],
  ['orangutan', 'orangutans', 1.4],
  ['bald eagle', 'bald eagles beak to tail', 0.9],
  ['great horned owl', 'great horned owls', 0.55],
  ['pigeon', 'stacked pigeons', 0.3],
  ['chicken', 'stacked chickens', 0.4],
  ['wild turkey', 'wild turkeys', 1.0],
  ['goldfish', 'goldfish nose to tail', 0.08],
  ['axolotl', 'axolotls nose to tail', 0.23],
  ['saltwater crocodile on its tail', 'saltwater crocodiles on their tails', 5],
  ['bumblebee', 'bumblebees nose to tail', 0.02],
  ['ant', 'ants nose to tail', 0.005],
  ['ladybug', 'stacked ladybugs', 0.007],
  ['guinea pig', 'guinea pigs nose to tail', 0.25],
  ['rabbit standing up', 'rabbits standing up', 0.4],
  ['pug', 'pugs', 0.3],
  ['golden retriever', 'golden retrievers', 0.6],
  ['standard poodle', 'standard poodles', 0.6],
  ['Irish wolfhound', 'Irish wolfhounds', 0.85],
  ['goat', 'goats', 0.8],
  ['sheep', 'sheep', 0.9],
  ['pig', 'pigs', 0.9],
  ['cow', 'cows', 1.5],
  ['donkey', 'donkeys', 1.2],
  ['Brachiosaurus', 'Brachiosauruses', 12],
  ['Stegosaurus', 'Stegosauruses', 4],
  ['Velociraptor (at the hip)', 'Velociraptors (at the hip)', 0.5],
  ['woolly mammoth', 'woolly mammoths', 3.4],
  ["giraffe's neck", "giraffes' necks", 2.0],

  // More food and drink
  ['cupcake', 'stacked cupcakes', 0.06],
  ['croissant', 'croissants end to end', 0.12],
  ['burrito', 'burritos end to end', 0.2],
  ['piece of sushi', 'stacked pieces of sushi', 0.03],
  ['wheel of Parmesan', 'stacked wheels of Parmesan', 0.22],
  ['bagel', 'stacked bagels', 0.03],
  ['waffle', 'stacked waffles', 0.025],
  ['frozen pizza', 'stacked frozen pizzas', 0.02],
  ['Twinkie', 'Twinkies end to end', 0.1],
  ['candy corn', 'stacked candy corns', 0.02],
  ['M&M', 'stacked M&Ms', 0.006],
  ['gummy bear', 'stacked gummy bears', 0.02],
  ['marshmallow Peep', 'stacked marshmallow Peeps', 0.05],
  ['jelly bean', 'jelly beans end to end', 0.02],
  ['coconut', 'stacked coconuts', 0.25],
  ['pumpkin', 'stacked pumpkins', 0.3],
  ['cabbage', 'stacked cabbages', 0.15],
  ['carrot', 'carrots end to end', 0.18],
  ['cucumber', 'cucumbers end to end', 0.2],
  ['potato', 'stacked potatoes', 0.08],
  ['avocado', 'stacked avocados', 0.1],
  ['lemon', 'stacked lemons', 0.08],
  ['grape', 'stacked grapes', 0.02],
  ['strawberry', 'stacked strawberries', 0.035],
  ['blueberry', 'stacked blueberries', 0.012],
  ['peanut', 'peanuts end to end', 0.03],
  ['eggplant', 'eggplants end to end', 0.2],
  ['wine bottle', 'stacked wine bottles', 0.3],
  ['2-liter soda bottle', 'stacked 2-liter soda bottles', 0.33],
  ['milk jug', 'stacked milk jugs', 0.25],
  ['beer keg', 'stacked beer kegs', 0.59],
  ['coffee mug', 'stacked coffee mugs', 0.095],
  ['birthday cake', 'stacked birthday cakes', 0.12],
  ['three-tier wedding cake', 'stacked three-tier wedding cakes', 0.9],

  // More small stuff
  ['playing card', 'stacked playing cards', 0.0003],
  ['sheet of paper', 'stacked sheets of paper', 0.0001],
  ['raindrop', 'stacked raindrops', 0.002],
  ['paperback book', 'stacked paperback books', 0.025],
  ['closed laptop', 'stacked closed laptops', 0.018],
  ['floppy disk', 'stacked floppy disks', 0.0033],
  ['VHS tape', 'stacked VHS tapes', 0.025],
  ['cassette tape', 'stacked cassette tapes', 0.017],
  ['Game Boy', 'Game Boys end to end', 0.148],
  ['house brick', 'stacked house bricks', 0.065],
  ['cinder block', 'stacked cinder blocks', 0.2],
  ['car tire', 'stacked car tires', 0.2],
  ['wooden pallet', 'stacked wooden pallets', 0.144],
  ['mattress', 'stacked mattresses', 0.25],

  // More household, sports and music
  ['toilet', 'stacked toilets', 0.76],
  ['grandfather clock', 'grandfather clocks', 2.0],
  ['Christmas tree', 'Christmas trees', 2.0],
  ['curbside mailbox', 'curbside mailboxes', 1.1],
  ['parking meter', 'parking meters', 1.4],
  ['British phone booth', 'British phone booths', 2.5],
  ['vending machine', 'stacked vending machines', 1.83],
  ['arcade cabinet', 'stacked arcade cabinets', 1.8],
  ['porta-potty', 'stacked porta-potties', 2.3],
  ['server rack', 'stacked server racks', 2.0],
  ['bicycle', 'stacked bicycles', 1.0],
  ['skateboard on end', 'skateboards on end', 0.8],
  ['surfboard on end', 'surfboards on end', 2.1],
  ['canoe on end', 'canoes on end', 5],
  ['snowboard', 'snowboards end to end', 1.55],
  ['ski', 'skis end to end', 1.7],
  ['hockey stick', 'hockey sticks end to end', 1.6],
  ['baseball bat', 'baseball bats end to end', 0.84],
  ['golf driver', 'golf drivers end to end', 1.15],
  ['pogo stick', 'pogo sticks', 1.2],
  ['acoustic guitar', 'acoustic guitars end to end', 1.0],
  ['violin', 'violins end to end', 0.6],
  ['double bass', 'double basses', 1.8],
  ['upright piano', 'stacked upright pianos', 1.2],
  ['concert harp', 'concert harps', 1.8],

  // Vehicles
  ['Lamborghini', 'stacked Lamborghinis', 1.13],
  ['Mini Cooper on end', 'Mini Coopers on end', 3.9],
  ['Smart car on end', 'Smart cars on end', 2.7],
  ['monster truck', 'stacked monster trucks', 3.7],
  ['semi truck', 'stacked semi trucks', 4.1],
  ['hot air balloon', 'hot air balloons', 21],
  ['Boeing 747 tail', 'Boeing 747 tails', 19.4],
  ['Space Shuttle launch stack', 'Space Shuttle launch stacks', 56],
  ['Goodyear Blimp on end', 'Goodyear Blimps on end', 75],
  ['Titanic on end', 'Titanics on end', 269],

  // More landmarks and nature
  ['Hollywood sign letter', 'Hollywood sign letters', 13.7],
  ['Mount Rushmore face', 'Mount Rushmore faces', 18],
  ['Great Sphinx of Giza', 'Great Sphinxes of Giza', 20],
  ['Colosseum', 'Colosseums', 48],
  ['Arc de Triomphe', 'Arcs de Triomphe', 50],
  ['Niagara Falls (Horseshoe)', 'Niagara Falls (Horseshoe)', 51],
  ['Sydney Opera House', 'Sydney Opera Houses', 65],
  ['Tower Bridge', 'Tower Bridges', 65],
  ['Taj Mahal', 'Taj Mahals', 73],
  ['wind turbine (to the hub)', 'wind turbines (to the hub)', 80],
  ['The Motherland Calls statue', 'Motherland Calls statues', 85],
  ['London Eye', 'London Eyes', 135],
  ['Kingda Ka roller coaster', 'Kingda Ka roller coasters', 139],
  ['Space Needle', 'Space Needles', 184],
  ['Gateway Arch', 'Gateway Arches', 192],
  ['Golden Gate Bridge tower', 'Golden Gate Bridge towers', 227],
  ['Petronas Tower', 'Petronas Towers', 452],
  ['Taipei 101', 'Taipei 101s', 508],
  ['One World Trade Center', 'One World Trade Centers', 541],
  ['CN Tower', 'CN Towers', 553],
  ['Shanghai Tower', 'Shanghai Towers', 632],
  ['Tokyo Skytree', 'Tokyo Skytrees', 634],
  ['Angel Falls', 'Angel Falls', 979],
  ['sunflower', 'sunflowers', 2.0],
  ['saguaro cactus', 'saguaro cacti', 12],
  ['oak tree', 'oak trees', 20],
];
