// Absurd units for sharing your height: [singular, plural, height in meters].
// Heights are rough, typical values (things that are usually flat are "stacked";
// long things are "end to end" or "on end"). Add more freely.
window.CLIMBER_UNITS = [
  // People and characters
  ['Hugh Jackman', 'Hugh Jackmans', 1.88],
  ['Danny DeVito', 'Danny DeVitos', 1.47],
  ["Shaquille O'Neal", "Shaquille O'Neals", 2.16],
  ['Yao Ming', 'Yao Mings', 2.29],
  ['Peter Dinklage', 'Peter Dinklages', 1.35],
  ['Robert Wadlow (tallest man ever)', 'Robert Wadlows (tallest man ever)', 2.72],
  ['average human', 'average humans', 1.7],
  ['hobbit', 'hobbits', 1.07],
  ['Yoda', 'Yodas', 0.66],
  ['Bigfoot (estimated)', 'Bigfoots (estimated)', 2.4],
  ['average snowman', 'average snowmen', 1.5],
  ['garden gnome', 'garden gnomes', 0.3],
  ['Barbie doll', 'Barbie dolls', 0.29],
  ['LEGO minifigure', 'LEGO minifigures', 0.04],

  // Animals
  ['African bush elephant', 'African bush elephants', 3.2],
  ['giraffe', 'giraffes', 5.5],
  ['ostrich', 'ostriches', 2.5],
  ['emu', 'emus', 1.75],
  ['emperor penguin', 'emperor penguins', 1.15],
  ['flamingo', 'flamingos', 1.2],
  ['kiwi bird', 'kiwi birds', 0.4],
  ['chihuahua', 'chihuahuas', 0.2],
  ['corgi', 'corgis', 0.27],
  ['dachshund', 'dachshunds', 0.2],
  ['Great Dane', 'Great Danes', 0.8],
  ['house cat', 'house cats', 0.25],
  ['hamster', 'stacked hamsters', 0.05],
  ['hedgehog', 'stacked hedgehogs', 0.1],
  ['meerkat on lookout', 'meerkats on lookout', 0.3],
  ['capybara', 'capybaras', 0.55],
  ['alpaca', 'alpacas', 0.9],
  ['llama', 'llamas', 1.8],
  ['Shetland pony', 'Shetland ponies', 1.0],
  ['horse', 'horses', 1.6],
  ['moose', 'moose', 1.9],
  ['red kangaroo', 'red kangaroos', 1.5],
  ['silverback gorilla', 'silverback gorillas', 1.7],
  ['grizzly bear standing up', 'grizzly bears standing up', 2.4],
  ['polar bear standing up', 'polar bears standing up', 2.5],
  ['narwhal tusk', 'narwhal tusks', 2.5],
  ['Komodo dragon on its tail', 'Komodo dragons on their tails', 2.6],
  ['Tyrannosaurus rex (at the hip)', 'Tyrannosaurus rexes (at the hip)', 3.7],
  ['blue whale balanced on its tail', 'blue whales balanced on their tails', 25],
  ['garden snail', 'stacked garden snails', 0.03],

  // Food and drink
  ['marshmallow', 'stacked marshmallows', 0.03],
  ['Big Mac', 'stacked Big Macs', 0.08],
  ['Oreo', 'stacked Oreos', 0.01],
  ['pancake', 'stacked pancakes', 0.012],
  ['donut', 'stacked donuts', 0.03],
  ['slice of toast', 'stacked slices of toast', 0.015],
  ['pizza box', 'stacked pizza boxes', 0.05],
  ['soda can', 'stacked soda cans', 0.122],
  ['Pringles can', 'stacked Pringles cans', 0.24],
  ['banana', 'bananas end to end', 0.18],
  ['baguette', 'baguettes end to end', 0.65],
  ['hot dog', 'hot dogs end to end', 0.15],
  ['watermelon', 'stacked watermelons', 0.3],
  ['pineapple', 'stacked pineapples', 0.3],
  ['chicken egg', 'stacked chicken eggs', 0.06],
  ['ostrich egg', 'stacked ostrich eggs', 0.15],
  ['cereal box', 'stacked cereal boxes', 0.3],
  ['ketchup bottle', 'stacked ketchup bottles', 0.2],

  // Small stuff
  ['LEGO brick', 'stacked LEGO bricks', 0.0096],
  ['credit card', 'stacked credit cards', 0.00076],
  ['penny', 'stacked pennies', 0.0015],
  ['poker chip', 'stacked poker chips', 0.0033],
  ['DVD', 'stacked DVDs', 0.0012],
  ['hockey puck', 'stacked hockey pucks', 0.0254],
  ['AA battery', 'AA batteries end to end', 0.05],
  ["Rubik's Cube", "stacked Rubik's Cubes", 0.057],
  ['rubber duck', 'stacked rubber ducks', 0.09],
  ['golf ball', 'stacked golf balls', 0.043],
  ['ping pong ball', 'stacked ping pong balls', 0.04],
  ['tennis ball', 'stacked tennis balls', 0.067],
  ['baseball', 'stacked baseballs', 0.074],
  ['soccer ball', 'stacked soccer balls', 0.22],
  ['bowling ball', 'stacked bowling balls', 0.218],
  ['bowling pin', 'stacked bowling pins', 0.38],
  ['pencil', 'pencils end to end', 0.19],
  ['crayon', 'crayons end to end', 0.09],
  ['Sharpie', 'Sharpies end to end', 0.14],
  ['smartphone', 'smartphones end to end', 0.15],
  ['toilet paper roll', 'stacked toilet paper rolls', 0.11],
  ['shoebox', 'stacked shoeboxes', 0.12],

  // Household and street
  ['toaster', 'stacked toasters', 0.2],
  ['microwave', 'stacked microwaves', 0.3],
  ['washing machine', 'stacked washing machines', 0.85],
  ['refrigerator', 'stacked refrigerators', 1.75],
  ['IKEA Billy bookcase', 'stacked IKEA Billy bookcases', 2.02],
  ['front door', 'front doors', 2.03],
  ['shopping cart', 'stacked shopping carts', 1.0],
  ['traffic cone', 'stacked traffic cones', 0.7],
  ['fire hydrant', 'stacked fire hydrants', 0.7],
  ['basketball hoop', 'basketball hoops', 3.05],
  ['shipping container', 'stacked shipping containers', 2.59],
  ['double-decker bus', 'stacked double-decker buses', 4.4],
  ['school bus on end', 'school buses on end', 12],
  ['Olympic diving platform', 'Olympic diving platforms', 10],

  // Trophies
  ['Oscar statuette', 'Oscar statuettes', 0.343],
  ['FIFA World Cup trophy', 'FIFA World Cup trophies', 0.368],
  ['Stanley Cup', 'Stanley Cups', 0.896],

  // Landmarks and giants
  ['Stonehenge stone', 'Stonehenge stones', 4.1],
  ['Christ the Redeemer', 'Christ the Redeemers', 30],
  ['Statue of Liberty (no pedestal)', 'Statues of Liberty (no pedestal)', 46],
  ['Leaning Tower of Pisa', 'Leaning Towers of Pisa', 56],
  ['General Sherman tree', 'General Sherman trees', 84],
  ['Big Ben tower', 'Big Ben towers', 96],
  ['Saturn V rocket', 'Saturn V rockets', 111],
  ['Hyperion (tallest tree)', 'Hyperions (tallest tree)', 116],
  ['Great Pyramid of Giza', 'Great Pyramids of Giza', 139],
  ['Washington Monument', 'Washington Monuments', 169],
  ['Eiffel Tower', 'Eiffel Towers', 330],
  ['Empire State Building', 'Empire State Buildings', 381],
  ['Burj Khalifa', 'Burj Khalifas', 828],
];
