// Absurd units for sharing your height: [singular, plural, height in meters].
// Heights are rough, typical values (things that are usually flat are "stacked";
// long things are "end to end" or "on end"). Add more freely.
window.CLIMBER_UNITS = [
  // People and characters
  ['Hugh Jackman', 'Hugh Jackmans', 1.88],
  ['Danny DeVito', 'Danny DeVitos', 1.47],
  ["Shaquille O'Neal", "Shaquille O'Neals", 2.16],
  ['Yao Ming', 'Yao Mings', 2.29],
  ['Peter Dinklage', 'Peter Dinklages', 1.35],
  ['Robert Wadlow (tallest man ever)', 'Robert Wadlows (tallest man ever)', 2.72],
  ['average human', 'average humans', 1.7],
  ['hobbit', 'hobbits', 1.07],
  ['Yoda', 'Yodas', 0.66],
  ['Bigfoot (estimated)', 'Bigfoots (estimated)', 2.4],
  ['average snowman', 'average snowmen', 1.5],
  ['garden gnome', 'garden gnomes', 0.3],
  ['Barbie doll', 'Barbie dolls', 0.29],
  ['LEGO minifigure', 'LEGO minifigures', 0.04],

  // Animals
  ['African bush elephant', 'African bush elephants', 3.2],
  ['giraffe', 'giraffes', 5.5],
  ['ostrich', 'ostriches', 2.5],
  ['emu', 'emus', 1.75],
  ['emperor penguin', 'emperor penguins', 1.15],
  ['flamingo', 'flamingos', 1.2],
  ['kiwi bird', 'kiwi birds', 0.4],
  ['chihuahua', 'chihuahuas', 0.2],
  ['corgi', 'corgis', 0.27],
  ['dachshund', 'dachshunds', 0.2],
  ['Great Dane', 'Great Danes', 0.8],
  ['house cat', 'house cats', 0.25],
  ['hamster', 'stacked hamsters', 0.05],
  ['hedgehog', 'stacked hedgehogs', 0.1],
  ['meerkat on lookout', 'meerkats on lookout', 0.3],
  ['capybara', 'capybaras', 0.55],
  ['alpaca', 'alpacas', 0.9],
  ['llama', 'llamas', 1.8],
  ['Shetland pony', 'Shetland ponies', 1.0],
  ['horse', 'horses', 1.6],
  ['moose', 'moose', 1.9],
  ['red kangaroo', 'red kangaroos', 1.5],
  ['silverback gorilla', 'silverback gorillas', 1.7],
  ['grizzly bear standing up', 'grizzly bears standing up', 2.4],
  ['polar bear standing up', 'polar bears standing up', 2.5],
  ['narwhal tusk', 'narwhal tusks', 2.5],
  ['Komodo dragon on its tail', 'Komodo dragons on their tails', 2.6],
  ['Tyrannosaurus rex (at the hip)', 'Tyrannosaurus rexes (at the hip)', 3.7],
  ['blue whale balanced on its tail', 'blue whales balanced on their tails', 25],
  ['garden snail', 'stacked garden snails', 0.03],

  // Food and drink
  ['marshmallow', 'stacked marshmallows', 0.03],
  ['Big Mac', 'stacked Big Macs', 0.08],
  ['Oreo', 'stacked Oreos', 0.01],
  ['pancake', 'stacked pancakes', 0.012],
  ['donut', 'stacked donuts', 0.03],
  ['slice of toast', 'stacked slices of toast', 0.015],
  ['pizza box', 'stacked pizza boxes', 0.05],
  ['soda can', 'stacked soda cans', 0.122],
  ['Pringles can', 'stacked Pringles cans', 0.24],
  ['banana', 'bananas end to end', 0.18],
  ['baguette', 'baguettes end to end', 0.65],
  ['hot dog', 'hot dogs end to end', 0.15],
  ['watermelon', 'stacked watermelons', 0.3],
  ['pineapple', 'stacked pineapples', 0.3],
  ['chicken egg', 'stacked chicken eggs', 0.06],
  ['ostrich egg', 'stacked ostrich eggs', 0.15],
  ['cereal box', 'stacked cereal boxes', 0.3],
  ['ketchup bottle', 'stacked ketchup bottles', 0.2],

  // Small stuff
  ['LEGO brick', 'stacked LEGO bricks', 0.0096],
  ['credit card', 'stacked credit cards', 0.00076],
  ['penny', 'stacked pennies', 0.0015],
  ['poker chip', 'stacked poker chips', 0.0033],
  ['DVD', 'stacked DVDs', 0.0012],
  ['hockey puck', 'stacked hockey pucks', 0.0254],
  ['AA battery', 'AA batteries end to end', 0.05],
  ["Rubik's Cube", "stacked Rubik's Cubes", 0.057],
  ['rubber duck', 'stacked rubber ducks', 0.09],
  ['golf ball', 'stacked golf balls', 0.043],
  ['ping pong ball', 'stacked ping pong balls', 0.04],
  ['tennis ball', 'stacked tennis balls', 0.067],
  ['baseball', 'stacked baseballs', 0.074],
  ['soccer ball', 'stacked soccer balls', 0.22],
  ['bowling ball', 'stacked bowling balls', 0.218],
  ['bowling pin', 'stacked bowling pins', 0.38],
  ['pencil', 'pencils end to end', 0.19],
  ['crayon', 'crayons end to end', 0.09],
  ['Sharpie', 'Sharpies end to end', 0.14],
  ['smartphone', 'smartphones end to end', 0.15],
  ['toilet paper roll', 'stacked toilet paper rolls', 0.11],
  ['shoebox', 'stacked shoeboxes', 0.12],

  // Household and street
  ['toaster', 'stacked toasters', 0.2],
  ['microwave', 'stacked microwaves', 0.3],
  ['washing machine', 'stacked washing machines', 0.85],
  ['refrigerator', 'stacked refrigerators', 1.75],
  ['IKEA Billy bookcase', 'stacked IKEA Billy bookcases', 2.02],
  ['front door', 'front doors', 2.03],
  ['shopping cart', 'stacked shopping carts', 1.0],
  ['traffic cone', 'stacked traffic cones', 0.7],
  ['fire hydrant', 'stacked fire hydrants', 0.7],
  ['basketball hoop', 'basketball hoops', 3.05],
  ['shipping container', 'stacked shipping containers', 2.59],
  ['double-decker bus', 'stacked double-decker buses', 4.4],
  ['school bus on end', 'school buses on end', 12],
  ['Olympic diving platform', 'Olympic diving platforms', 10],

  // Trophies
  ['Oscar statuette', 'Oscar statuettes', 0.343],
  ['FIFA World Cup trophy', 'FIFA World Cup trophies', 0.368],
  ['Stanley Cup', 'Stanley Cups', 0.896],

  // Landmarks and giants
  ['Stonehenge stone', 'Stonehenge stones', 4.1],
  ['Christ the Redeemer', 'Christ the Redeemers', 30],
  ['Statue of Liberty (no pedestal)', 'Statues of Liberty (no pedestal)', 46],
  ['Leaning Tower of Pisa', 'Leaning Towers of Pisa', 56],
  ['General Sherman tree', 'General Sherman trees', 84],
  ['Big Ben tower', 'Big Ben towers', 96],
  ['Saturn V rocket', 'Saturn V rockets', 111],
  ['Hyperion (tallest tree)', 'Hyperions (tallest tree)', 116],
  ['Great Pyramid of Giza', 'Great Pyramids of Giza', 139],
  ['Washington Monument', 'Washington Monuments', 169],
  ['Eiffel Tower', 'Eiffel Towers', 330],
  ['Empire State Building', 'Empire State Buildings', 381],
  ['Burj Khalifa', 'Burj Khalifas', 828],
  // More people and characters
  ['Michael Jordan', 'Michael Jordans', 1.98],
  ['LeBron James', 'LeBron Jameses', 2.06],
  ['Victor Wembanyama', 'Victor Wembanyamas', 2.24],
  ['Usain Bolt', 'Usain Bolts', 1.95],
  ['Simone Biles', 'Simone Bileses', 1.42],
  ['Lionel Messi', 'Lionel Messis', 1.7],
  ['Abraham Lincoln', 'Abraham Lincolns', 1.93],
  ['Napoleon', 'Napoleons', 1.69],
  ['Peter the Great', 'Peters the Great', 2.03],
  ['André the Giant', 'André the Giants', 2.24],
  ['Rumeysa Gelgi (tallest woman)', 'Rumeysa Gelgis (tallest woman)', 2.15],
  ['newborn baby', 'newborn babies', 0.5],
  ['toddler', 'toddlers', 0.85],
  ['Shrek', 'Shreks', 2.13],
  ['Mario', 'Marios', 1.55],
  ['Big Bird', 'Big Birds', 2.49],
  ['Darth Vader', 'Darth Vaders', 2.02],
  ['Chewbacca', 'Chewbaccas', 2.28],
  ['Hagrid (book version)', 'Hagrids (book version)', 3.5],
  ['Optimus Prime', 'Optimus Primes', 8.5],
  ['Iron Giant', 'Iron Giants', 15],
  ['Stay Puft Marshmallow Man', 'Stay Puft Marshmallow Men', 34],
  ['Godzilla', 'Godzillas', 108],
  ['The Thinker statue', 'Thinker statues', 1.86],
  ["Michelangelo's David", "Michelangelo's Davids", 5.17],
  ['Venus de Milo', 'Venuses de Milo', 2.04],
  ['Manneken Pis', 'Manneken Pises', 0.61],
  ['Little Mermaid statue', 'Little Mermaid statues', 1.25],
  ['Easter Island moai', 'Easter Island moai', 4],

  // More animals
  ['lion', 'lions', 1.2],
  ['tiger', 'tigers', 1.0],
  ['cheetah', 'cheetahs', 0.8],
  ['gray wolf', 'gray wolves', 0.8],
  ['red fox', 'red foxes', 0.4],
  ['raccoon', 'stacked raccoons', 0.3],
  ['hippopotamus', 'hippopotamuses', 1.5],
  ['rhinoceros', 'rhinoceroses', 1.8],
  ['camel', 'camels', 2.0],
  ['zebra', 'zebras', 1.4],
  ['okapi', 'okapis', 1.6],
  ['bison', 'bison', 1.8],
  ['giant panda', 'giant pandas', 0.8],
  ['chimpanzee', 'chimpanzees', 1.2],
  ['orangutan', 'orangutans', 1.4],
  ['bald eagle', 'bald eagles beak to tail', 0.9],
  ['great horned owl', 'great horned owls', 0.55],
  ['pigeon', 'stacked pigeons', 0.3],
  ['chicken', 'stacked chickens', 0.4],
  ['wild turkey', 'wild turkeys', 1.0],
  ['goldfish', 'goldfish nose to tail', 0.08],
  ['axolotl', 'axolotls nose to tail', 0.23],
  ['saltwater crocodile on its tail', 'saltwater crocodiles on their tails', 5],
  ['bumblebee', 'bumblebees nose to tail', 0.02],
  ['ant', 'ants nose to tail', 0.005],
  ['ladybug', 'stacked ladybugs', 0.007],
  ['guinea pig', 'guinea pigs nose to tail', 0.25],
  ['rabbit standing up', 'rabbits standing up', 0.4],
  ['pug', 'pugs', 0.3],
  ['golden retriever', 'golden retrievers', 0.6],
  ['standard poodle', 'standard poodles', 0.6],
  ['Irish wolfhound', 'Irish wolfhounds', 0.85],
  ['goat', 'goats', 0.8],
  ['sheep', 'sheep', 0.9],
  ['pig', 'pigs', 0.9],
  ['cow', 'cows', 1.5],
  ['donkey', 'donkeys', 1.2],
  ['Brachiosaurus', 'Brachiosauruses', 12],
  ['Stegosaurus', 'Stegosauruses', 4],
  ['Velociraptor (at the hip)', 'Velociraptors (at the hip)', 0.5],
  ['woolly mammoth', 'woolly mammoths', 3.4],
  ["giraffe's neck", "giraffes' necks", 2.0],

  // More food and drink
  ['cupcake', 'stacked cupcakes', 0.06],
  ['croissant', 'croissants end to end', 0.12],
  ['burrito', 'burritos end to end', 0.2],
  ['piece of sushi', 'stacked pieces of sushi', 0.03],
  ['wheel of Parmesan', 'stacked wheels of Parmesan', 0.22],
  ['bagel', 'stacked bagels', 0.03],
  ['waffle', 'stacked waffles', 0.025],
  ['frozen pizza', 'stacked frozen pizzas', 0.02],
  ['Twinkie', 'Twinkies end to end', 0.1],
  ['candy corn', 'stacked candy corns', 0.02],
  ['M&M', 'stacked M&Ms', 0.006],
  ['gummy bear', 'stacked gummy bears', 0.02],
  ['marshmallow Peep', 'stacked marshmallow Peeps', 0.05],
  ['jelly bean', 'jelly beans end to end', 0.02],
  ['coconut', 'stacked coconuts', 0.25],
  ['pumpkin', 'stacked pumpkins', 0.3],
  ['cabbage', 'stacked cabbages', 0.15],
  ['carrot', 'carrots end to end', 0.18],
  ['cucumber', 'cucumbers end to end', 0.2],
  ['potato', 'stacked potatoes', 0.08],
  ['avocado', 'stacked avocados', 0.1],
  ['lemon', 'stacked lemons', 0.08],
  ['grape', 'stacked grapes', 0.02],
  ['strawberry', 'stacked strawberries', 0.035],
  ['blueberry', 'stacked blueberries', 0.012],
  ['peanut', 'peanuts end to end', 0.03],
  ['eggplant', 'eggplants end to end', 0.2],
  ['wine bottle', 'stacked wine bottles', 0.3],
  ['2-liter soda bottle', 'stacked 2-liter soda bottles', 0.33],
  ['milk jug', 'stacked milk jugs', 0.25],
  ['beer keg', 'stacked beer kegs', 0.59],
  ['coffee mug', 'stacked coffee mugs', 0.095],
  ['birthday cake', 'stacked birthday cakes', 0.12],
  ['three-tier wedding cake', 'stacked three-tier wedding cakes', 0.9],

  // More small stuff
  ['playing card', 'stacked playing cards', 0.0003],
  ['sheet of paper', 'stacked sheets of paper', 0.0001],
  ['raindrop', 'stacked raindrops', 0.002],
  ['paperback book', 'stacked paperback books', 0.025],
  ['closed laptop', 'stacked closed laptops', 0.018],
  ['floppy disk', 'stacked floppy disks', 0.0033],
  ['VHS tape', 'stacked VHS tapes', 0.025],
  ['cassette tape', 'stacked cassette tapes', 0.017],
  ['Game Boy', 'Game Boys end to end', 0.148],
  ['house brick', 'stacked house bricks', 0.065],
  ['cinder block', 'stacked cinder blocks', 0.2],
  ['car tire', 'stacked car tires', 0.2],
  ['wooden pallet', 'stacked wooden pallets', 0.144],
  ['mattress', 'stacked mattresses', 0.25],

  // More household, sports and music
  ['toilet', 'stacked toilets', 0.76],
  ['grandfather clock', 'grandfather clocks', 2.0],
  ['Christmas tree', 'Christmas trees', 2.0],
  ['curbside mailbox', 'curbside mailboxes', 1.1],
  ['parking meter', 'parking meters', 1.4],
  ['British phone booth', 'British phone booths', 2.5],
  ['vending machine', 'stacked vending machines', 1.83],
  ['arcade cabinet', 'stacked arcade cabinets', 1.8],
  ['porta-potty', 'stacked porta-potties', 2.3],
  ['server rack', 'stacked server racks', 2.0],
  ['bicycle', 'stacked bicycles', 1.0],
  ['skateboard on end', 'skateboards on end', 0.8],
  ['surfboard on end', 'surfboards on end', 2.1],
  ['canoe on end', 'canoes on end', 5],
  ['snowboard', 'snowboards end to end', 1.55],
  ['ski', 'skis end to end', 1.7],
  ['hockey stick', 'hockey sticks end to end', 1.6],
  ['baseball bat', 'baseball bats end to end', 0.84],
  ['golf driver', 'golf drivers end to end', 1.15],
  ['pogo stick', 'pogo sticks', 1.2],
  ['acoustic guitar', 'acoustic guitars end to end', 1.0],
  ['violin', 'violins end to end', 0.6],
  ['double bass', 'double basses', 1.8],
  ['upright piano', 'stacked upright pianos', 1.2],
  ['concert harp', 'concert harps', 1.8],

  // Vehicles
  ['Lamborghini', 'stacked Lamborghinis', 1.13],
  ['Mini Cooper on end', 'Mini Coopers on end', 3.9],
  ['Smart car on end', 'Smart cars on end', 2.7],
  ['monster truck', 'stacked monster trucks', 3.7],
  ['semi truck', 'stacked semi trucks', 4.1],
  ['hot air balloon', 'hot air balloons', 21],
  ['Boeing 747 tail', 'Boeing 747 tails', 19.4],
  ['Space Shuttle launch stack', 'Space Shuttle launch stacks', 56],
  ['Goodyear Blimp on end', 'Goodyear Blimps on end', 75],
  ['Titanic on end', 'Titanics on end', 269],

  // More landmarks and nature
  ['Hollywood sign letter', 'Hollywood sign letters', 13.7],
  ['Mount Rushmore face', 'Mount Rushmore faces', 18],
  ['Great Sphinx of Giza', 'Great Sphinxes of Giza', 20],
  ['Colosseum', 'Colosseums', 48],
  ['Arc de Triomphe', 'Arcs de Triomphe', 50],
  ['Niagara Falls (Horseshoe)', 'Niagara Falls (Horseshoe)', 51],
  ['Sydney Opera House', 'Sydney Opera Houses', 65],
  ['Tower Bridge', 'Tower Bridges', 65],
  ['Taj Mahal', 'Taj Mahals', 73],
  ['wind turbine (to the hub)', 'wind turbines (to the hub)', 80],
  ['The Motherland Calls statue', 'Motherland Calls statues', 85],
  ['London Eye', 'London Eyes', 135],
  ['Kingda Ka roller coaster', 'Kingda Ka roller coasters', 139],
  ['Space Needle', 'Space Needles', 184],
  ['Gateway Arch', 'Gateway Arches', 192],
  ['Golden Gate Bridge tower', 'Golden Gate Bridge towers', 227],
  ['Petronas Tower', 'Petronas Towers', 452],
  ['Taipei 101', 'Taipei 101s', 508],
  ['One World Trade Center', 'One World Trade Centers', 541],
  ['CN Tower', 'CN Towers', 553],
  ['Shanghai Tower', 'Shanghai Towers', 632],
  ['Tokyo Skytree', 'Tokyo Skytrees', 634],
  ['Angel Falls', 'Angel Falls', 979],
  ['sunflower', 'sunflowers', 2.0],
  ['saguaro cactus', 'saguaro cacti', 12],
  ['oak tree', 'oak trees', 20],
  // Pokémon (official Pokédex heights)
  ['Pikachu', 'Pikachus', 0.4],
  ['Snorlax', 'Snorlaxes', 2.1],
  ['Onix', 'Onixes', 8.8],
  ['Wailord', 'Wailords', 14.5],
  ['Charizard', 'Charizards', 1.7],
  ['Bulbasaur', 'Bulbasaurs', 0.7],
  ['Squirtle', 'Squirtles', 0.5],
  ['Charmander', 'Charmanders', 0.6],
  ['Jigglypuff', 'Jigglypuffs', 0.5],
  ['Magikarp', 'Magikarps', 0.9],
  ['Gyarados', 'Gyaradoses', 6.5],
  ['Mewtwo', 'Mewtwos', 2.0],
  ['Eevee', 'Eevees', 0.3],
  ['Psyduck', 'Psyducks', 0.8],
  ['Lapras', 'Lapras', 2.5],
  ['Dragonite', 'Dragonites', 2.2],
  ['Gengar', 'Gengars', 1.5],
  ['Ditto', 'stacked Dittos', 0.3],
  ['Steelix', 'Steelixes', 9.2],
  ['Rayquaza', 'Rayquazas', 7.0],
  ['Lugia', 'Lugias', 5.2],
  ['Eternatus', 'Eternatuses', 20],

  // Anime, games and cartoons
  ['Goku', 'Gokus', 1.75],
  ['Naruto', 'Narutos', 1.66],
  ['Monkey D. Luffy', 'Monkey D. Luffys', 1.74],
  ['Sonic the Hedgehog', 'Sonic the Hedgehogs', 1.0],
  ['Kirby', 'stacked Kirbys', 0.2],
  ['Master Chief (in armor)', 'Master Chiefs (in armor)', 2.18],
  ['SpongeBob', 'stacked SpongeBobs', 0.1],
  ['R2-D2', 'R2-D2s', 1.09],
  ['C-3PO', 'C-3POs', 1.67],
  ['Grogu', 'Grogus', 0.4],
  ['TARDIS', 'stacked TARDISes', 2.85],
  ['Jaws (on its tail)', 'Jawses (on their tails)', 7.6],

  // Athletes
  ['Tom Brady', 'Tom Bradys', 1.93],
  ['Patrick Mahomes', 'Patrick Mahomeses', 1.88],
  ['Travis Kelce', 'Travis Kelces', 1.96],
  ['Stephen Curry', 'Stephen Currys', 1.88],
  ['Kevin Durant', 'Kevin Durants', 2.11],
  ['Giannis Antetokounmpo', 'Giannis Antetokounmpos', 2.11],
  ['Nikola Jokić', 'Nikola Jokićs', 2.11],
  ['Kobe Bryant', 'Kobe Bryants', 1.98],
  ['Muggsy Bogues', 'Muggsy Bogueses', 1.6],
  ['Manute Bol', 'Manute Bols', 2.31],
  ['Spud Webb', 'Spud Webbs', 1.68],
  ['Wilt Chamberlain', 'Wilt Chamberlains', 2.16],
  ['Kareem Abdul-Jabbar', 'Kareem Abdul-Jabbars', 2.18],
  ['Caitlin Clark', 'Caitlin Clarks', 1.83],
  ['Brittney Griner', 'Brittney Griners', 2.06],
  ['Serena Williams', 'Serena Williamses', 1.75],
  ['Roger Federer', 'Roger Federers', 1.85],
  ['Rafael Nadal', 'Rafael Nadals', 1.85],
  ['Novak Djokovic', 'Novak Djokovics', 1.88],
  ['John Isner', 'John Isners', 2.08],
  ['Cristiano Ronaldo', 'Cristiano Ronaldos', 1.87],
  ['Peter Crouch', 'Peter Crouches', 2.01],
  ['Zlatan Ibrahimović', 'Zlatan Ibrahimovićs', 1.95],
  ['Erling Haaland', 'Erling Haalands', 1.95],
  ['Diego Maradona', 'Diego Maradonas', 1.65],
  ['Pelé', 'Pelés', 1.73],
  ['Wayne Gretzky', 'Wayne Gretzkys', 1.83],
  ['Zdeno Chára', 'Zdeno Cháras', 2.06],
  ['Michael Phelps', 'Michael Phelpses', 1.93],
  ['Katie Ledecky', 'Katie Ledeckys', 1.83],
  ['Shohei Ohtani', 'Shohei Ohtanis', 1.93],
  ['Aaron Judge', 'Aaron Judges', 2.01],
  ['Jose Altuve', 'Jose Altuves', 1.68],
  ['Tiger Woods', 'Tiger Woodses', 1.85],
  ['Tony Hawk', 'Tony Hawks', 1.88],
  ['Muhammad Ali', 'Muhammad Alis', 1.91],
  ['Mike Tyson', 'Mike Tysons', 1.78],
  ['Tyson Fury', 'Tyson Furys', 2.06],
  ['Bruce Lee', 'Bruce Lees', 1.72],
  ['Jackie Chan', 'Jackie Chans', 1.74],
  ['Hafþór Björnsson (The Mountain)', 'Hafþór Björnssons (The Mountain)', 2.06],

  // Celebrities
  ['Taylor Swift', 'Taylor Swifts', 1.8],
  ['Dwayne "The Rock" Johnson', 'Dwayne "The Rock" Johnsons', 1.96],
  ['Arnold Schwarzenegger', 'Arnold Schwarzeneggers', 1.88],
  ['Jeff Goldblum', 'Jeff Goldblums', 1.94],
  ['Gwendoline Christie', 'Gwendoline Christies', 1.91],
  ['Snoop Dogg', 'Snoop Doggs', 1.93],
  ['Dolly Parton', 'Dolly Partons', 1.52],
  ['Ariana Grande', 'Ariana Grandes', 1.53],
  ['Lady Gaga', 'Lady Gagas', 1.55],
  ['Prince', 'Princes', 1.57],
  ['Freddie Mercury', 'Freddie Mercurys', 1.77],
  ['Elvis Presley', 'Elvis Presleys', 1.82],

  // Dog, cat and horse breeds
  ['Shiba Inu', 'Shiba Inus', 0.4],
  ['Pomeranian', 'Pomeranians', 0.2],
  ['Bernese Mountain Dog', 'Bernese Mountain Dogs', 0.65],
  ['Borzoi', 'Borzois', 0.75],
  ['Saint Bernard', 'Saint Bernards', 0.8],
  ['Newfoundland', 'Newfoundlands', 0.7],
  ['Basset Hound', 'Basset Hounds', 0.35],
  ['Dalmatian', 'Dalmatians', 0.58],
  ['French Bulldog', 'French Bulldogs', 0.3],
  ['Greyhound', 'Greyhounds', 0.73],
  ['Whippet', 'Whippets', 0.5],
  ['Border Collie', 'Border Collies', 0.53],
  ['Australian Shepherd', 'Australian Shepherds', 0.55],
  ['Siberian Husky', 'Siberian Huskies', 0.56],
  ['Komondor', 'Komondors', 0.75],
  ['Puli', 'Pulis', 0.43],
  ['Samoyed', 'Samoyeds', 0.55],
  ['Afghan Hound', 'Afghan Hounds', 0.7],
  ['Cavalier King Charles Spaniel', 'Cavalier King Charles Spaniels', 0.31],
  ['Doberman', 'Dobermans', 0.68],
  ['German Shepherd', 'German Shepherds', 0.62],
  ['Beagle', 'Beagles', 0.38],
  ['Yorkshire Terrier', 'Yorkshire Terriers', 0.2],
  ['Labrador', 'Labradors', 0.57],
  ['Maine Coon', 'Maine Coons', 0.4],
  ['Clydesdale', 'Clydesdales', 1.8],
  ['Falabella miniature horse', 'Falabella miniature horses', 0.8],
  ['Highland cow', 'Highland cows', 1.1],

  // Odd and wonderful animals
  ['blobfish', 'stacked blobfish', 0.3],
  ['pangolin', 'pangolins nose to tail', 0.8],
  ['aye-aye', 'aye-ayes', 0.4],
  ['shoebill stork', 'shoebill storks', 1.4],
  ['secretary bird', 'secretary birds', 1.3],
  ['cassowary', 'cassowaries', 1.7],
  ['kakapo', 'kakapos', 0.6],
  ['quokka', 'quokkas', 0.5],
  ['fennec fox', 'fennec foxes', 0.2],
  ['tapir', 'tapirs', 1.0],
  ['saiga antelope', 'saiga antelopes', 0.75],
  ['mantis shrimp', 'mantis shrimp nose to tail', 0.1],
  ['tardigrade', 'tardigrades nose to tail', 0.0005],
  ['naked mole-rat', 'naked mole-rats nose to tail', 0.08],
  ['marabou stork', 'marabou storks', 1.5],
  ['harpy eagle', 'harpy eagles', 1.0],
  ['pygmy hippo', 'pygmy hippos', 0.85],
  ['manatee on its tail', 'manatees on their tails', 3],
  ['ocean sunfish (fin to fin)', 'ocean sunfish (fin to fin)', 2.5],
  ['coelacanth on its tail', 'coelacanths on their tails', 2.0],
  ['giant squid on end', 'giant squid on end', 12],

  // Extinct giants
  ['dodo', 'dodos', 1.0],
  ['giant moa', 'giant moas', 3.6],
  ['elephant bird', 'elephant birds', 3.0],
  ['Triceratops', 'Triceratopses', 3.0],
  ['Ankylosaurus', 'Ankylosauruses', 1.7],
  ['Paraceratherium', 'Paraceratheriums', 4.8],
  ['megalodon on its tail', 'megalodons on their tails', 15],
  ['Titanoboa on its tail', 'Titanoboas on their tails', 13],

  // Snacks and treats
  ['Pop-Tart', 'stacked Pop-Tarts', 0.01],
  ['Hot Pocket', 'stacked Hot Pockets', 0.04],
  ['Tim Tam', 'stacked Tim Tams', 0.012],
  ['Jaffa Cake', 'stacked Jaffa Cakes', 0.008],
  ['stroopwafel', 'stacked stroopwafels', 0.007],
  ['macaron', 'stacked macarons', 0.02],
  ['Kinder Surprise egg', 'stacked Kinder Surprise eggs', 0.06],
  ['Toblerone bar', 'Toblerone bars end to end', 0.21],
  ['Pocky stick', 'Pocky sticks end to end', 0.13],
  ['Babybel cheese', 'stacked Babybel cheeses', 0.02],
  ['can of Spam', 'stacked cans of Spam', 0.08],
  ['Ferrero Rocher', 'stacked Ferrero Rochers', 0.03],
  ['mochi', 'stacked mochi', 0.03],
  ['onigiri', 'stacked onigiri', 0.07],
  ['sourdough loaf', 'stacked sourdough loaves', 0.12],

  // Toys, games and collectibles
  ['Funko Pop', 'stacked Funko Pops', 0.095],
  ['Tamagotchi', 'stacked Tamagotchis', 0.05],
  ['Furby', 'stacked Furbies', 0.15],
  ['Beanie Baby', 'stacked Beanie Babies', 0.2],
  ['American Girl doll', 'American Girl dolls', 0.46],
  ['original G.I. Joe', 'original G.I. Joes', 0.3],
  ['Hot Wheels car', 'Hot Wheels cars end to end', 0.075],
  ['Pez dispenser', 'stacked Pez dispensers', 0.11],
  ['Slinky', 'stacked Slinkys', 0.06],
  ['Magic 8 Ball', 'stacked Magic 8 Balls', 0.1],
  ['lava lamp', 'stacked lava lamps', 0.42],
  ['Jenga block', 'stacked Jenga blocks', 0.015],
  ['fresh Jenga tower', 'fresh Jenga towers', 0.27],
  ['d20', 'stacked d20s', 0.02],
  ['meeple', 'stacked meeples', 0.016],
  ['chess king', 'stacked chess kings', 0.095],
  ['Monopoly house', 'stacked Monopoly houses', 0.01],
  ['Warhammer miniature', 'stacked Warhammer miniatures', 0.032],
  ['sleeved Magic: The Gathering card', 'stacked sleeved Magic: The Gathering cards', 0.0005],
  ['Pokémon card', 'stacked Pokémon cards', 0.0003],
  ['yo-yo', 'stacked yo-yos', 0.06],

  // Retro tech
  ['NES cartridge', 'NES cartridges end to end', 0.133],
  ['Nintendo 64 cartridge', 'Nintendo 64 cartridges end to end', 0.116],
  ['iPod Classic', 'iPod Classics end to end', 0.104],
  ['Nokia 3310', 'Nokia 3310s end to end', 0.113],
  ['original Macintosh', 'stacked original Macintoshes', 0.34],
  ['PlayStation 2 (standing)', 'stacked PlayStation 2s (standing)', 0.3],
  ['vinyl LP', 'stacked vinyl LPs', 0.0015],

  // Instruments
  ['didgeridoo', 'didgeridoos end to end', 1.4],
  ['alphorn', 'alphorns end to end', 3.5],
  ['soprano ukulele', 'soprano ukuleles end to end', 0.53],
  ['banjo', 'banjos end to end', 0.95],
  ['triangle (the instrument)', 'stacked triangles (the instrument)', 0.18],
  ['kazoo', 'kazoos end to end', 0.12],
  ['cowbell', 'stacked cowbells', 0.15],
  ['Fender Stratocaster', 'Fender Stratocasters end to end', 0.99],
  ['Marshall stack', 'Marshall stacks', 1.8],
  ['drumstick', 'drumsticks end to end', 0.41],
  ['harmonica', 'harmonicas end to end', 0.1],
  ['oboe', 'oboes end to end', 0.65],
  ['bassoon', 'bassoons end to end', 1.34],

  // Hobbies and sports gear
  ['knitting needle', 'knitting needles end to end', 0.35],
  ['ball of yarn', 'stacked balls of yarn', 0.1],
  ['cast iron skillet', 'stacked cast iron skillets', 0.05],
  ['Weber kettle grill', 'stacked Weber kettle grills', 1.0],
  ['Stanley tumbler', 'stacked Stanley tumblers', 0.31],
  ['pickleball paddle', 'pickleball paddles end to end', 0.4],
  ['disc golf disc', 'stacked disc golf discs', 0.02],
  ['curling stone', 'stacked curling stones', 0.11],
  ['cricket bat', 'cricket bats end to end', 0.96],
  ['lacrosse stick', 'lacrosse sticks end to end', 1.0],
  ['dartboard (to the bullseye)', 'dartboards (to the bullseye)', 1.73],
  ['pool cue', 'pool cues end to end', 1.47],
  ['snooker ball', 'stacked snooker balls', 0.0525],
  ['badminton shuttlecock', 'stacked badminton shuttlecocks', 0.07],
  ['fencing foil', 'fencing foils end to end', 1.1],
  ['javelin', 'javelins end to end', 2.6],
  ['high jump world record bar', 'high jump world record bars', 2.45],
  ['carabiner', 'carabiners end to end', 0.1],
  ['60 m climbing rope', '60 m climbing ropes', 60],
  ['bouldering wall', 'bouldering walls', 4.5],
  ['speed climbing wall', 'speed climbing walls', 15],
  ['El Capitan', 'El Capitans', 914],
  ['volleyball net', 'volleyball nets', 2.43],
  ['soccer goal', 'soccer goals', 2.44],
  ['hockey net', 'stacked hockey nets', 1.22],
  ['NFL goalpost', 'NFL goalposts', 13.7],
  ['Green Monster (Fenway Park)', 'Green Monsters (Fenway Park)', 11.3],
  ['Larry O\'Brien Trophy', 'Larry O\'Brien Trophies', 0.61],
  ['Lombardi Trophy', 'Lombardi Trophies', 0.56],
  ['Claret Jug', 'Claret Jugs', 0.52],
  ['Ashes urn', 'Ashes urns', 0.11],

  // Vehicles and space
  ['Tesla Cybertruck', 'stacked Tesla Cybertrucks', 1.79],
  ['DeLorean', 'stacked DeLoreans', 1.14],
  ['VW Beetle', 'stacked VW Beetles', 1.5],
  ['Vespa', 'stacked Vespas', 1.1],
  ['Formula 1 car', 'stacked Formula 1 cars', 0.95],
  ['Venetian gondola on end', 'Venetian gondolas on end', 11],
  ['Curiosity rover', 'stacked Curiosity rovers', 2.2],
  ['Apollo lunar module', 'stacked Apollo lunar modules', 7],
  ['Sputnik 1', 'stacked Sputnik 1s', 0.58],
  ['Hubble Space Telescope on end', 'Hubble Space Telescopes on end', 13.2],
  ['Falcon 9 rocket', 'Falcon 9 rockets', 70],
  ['SLS rocket', 'SLS rockets', 98],
  ['Starship (full stack)', 'Starships (full stack)', 121],

  // History, myth and roadside oddities
  ['Colossus of Rhodes', 'Colossi of Rhodes', 33],
  ['terracotta warrior', 'terracotta warriors', 1.8],
  ['Paul Bunyan statue (Bemidji)', 'Paul Bunyan statues (Bemidji)', 5.5],

  // Plants
  ['Venus flytrap', 'stacked Venus flytraps', 0.1],
  ['corpse flower', 'corpse flowers', 3.0],
  ['Rafflesia flower', 'stacked Rafflesia flowers', 1.0],
  ['baobab tree', 'baobab trees', 20],
  ['giant kelp stalk', 'giant kelp stalks', 30],

  // Old and odd units
  ['smoot', 'smoots', 1.7],
  ['cubit', 'cubits', 0.457],
  ['fathom', 'fathoms', 1.83],
  ['hand (horse height)', 'hands (horse height)', 0.1016],
  ['furlong on end', 'furlongs on end', 201],
  ['light-nanosecond', 'light-nanoseconds', 0.2998],
];
